; Rebol []
; *****************************************************************************
; Title: Rebol core tests
; Copyright:
;     2012 REBOL Technologies
;     2013 Saphirion AG
; Author:
;     Carl Sassenrath, Ladislav Mecir, Andreas Bolka, Brian Hawley, John K
; License:
;     Licensed under the Apache License, Version 2.0 (the "License");
;     you may not use this file except in compliance with the License.
;     You may obtain a copy of the License at
;
;     http://www.apache.org/licenses/LICENSE-2.0
;
;     Unless required by applicable law or agreed to in writing, software
;     distributed under the License is distributed on an "AS IS" BASIS,
;     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;     See the License for the specific language governing permissions and
;     limitations under the License.
; *****************************************************************************
%parse-tests.r

%natives/action.test.reb
%datatypes/binary.test.reb
%datatypes/bitset.test.reb
%datatypes/block.test.reb
%datatypes/char.test.reb
%datatypes/closure.test.reb
%datatypes/datatype.test.reb
%datatypes/date.test.reb
%datatypes/decimal.test.reb
%datatypes/email.test.reb
%datatypes/error.test.reb
%datatypes/event.test.reb
%datatypes/file.test.reb
%datatypes/function.test.reb
%datatypes/get-path.test.reb
%datatypes/get-word.test.reb
%datatypes/gob.test.reb
%datatypes/hash.test.reb
%datatypes/image.test.reb
%datatypes/integer.test.reb
%datatypes/issue.test.reb
%datatypes/list.test.reb
%datatypes/lit-path.test.reb
%datatypes/lit-word.test.reb
%datatypes/logic.test.reb
%datatypes/map.test.reb
%datatypes/module.test.reb
%datatypes/money.test.reb
%datatypes/native.test.reb
%natives/none.test.reb
%datatypes/object.test.reb
%datatypes/op.test.reb
%datatypes/pair.test.reb
%datatypes/paren.test.reb
%datatypes/path.test.reb
%datatypes/percent.test.reb
%datatypes/port.test.reb
%datatypes/refinement.test.reb
%datatypes/set-path.test.reb
%datatypes/set-word.test.reb
%datatypes/string.test.reb
%datatypes/symbol.test.reb
%datatypes/time.test.reb
%datatypes/tuple.test.reb
%datatypes/typeset.test.reb
%natives/unset.test.reb
%datatypes/url.test.reb
%datatypes/vector.test.reb
%datatypes/word.test.reb
%comparison/lesserq.test.reb
%comparison/maximum-of.test.reb
%comparison/equalq.test.reb
%comparison/equivq.test.reb
%comparison/sameq.test.reb
%comparison/strict-equalq.test.reb
%comparison/strict-not-equalq.test.reb
%natives/bind.test.reb
%context/boundq.test.reb
%context/bindq.test.reb
%natives/resolve.test.reb
%natives/set.test.reb
%natives/unset.test.reb
%context/use.test.reb
%context/valueq.test.reb
%natives/all.test.reb
%natives/any.test.reb
%natives/apply.test.reb
%natives/attempt.test.reb
%natives/break.test.reb
%natives/case.test.reb
%natives/catch.test.reb
%natives/compose.test.reb
%natives/continue.test.reb
%control/disarm.test.reb
%natives/do.test.reb
%natives/either.test.reb
%control/else.test.reb
%natives/exit.test.reb
%natives/for.test.reb
%control/forall.test.reb
%natives/for-each.test.reb
%natives/forever.test.reb
%control/forskip.test.reb
%natives/halt.test.reb
%natives/if.test.reb
%natives/loop.test.reb
%natives/map-each.test.reb
%natives/reduce.test.reb
%natives/remove-each.test.reb
%natives/repeat.test.reb
%natives/return.test.reb
%natives/switch.test.reb
%natives/throw.test.reb
%control/try.test.reb
%natives/unless.test.reb
%natives/until.test.reb
%natives/wait.test.reb
%natives/while.test.reb
%natives/quit.test.reb
%convert/as-binary.test.reb
%convert/as-string.test.reb
%convert/encode.test.reb
%convert/load.test.reb
%natives/mold.test.reb
%natives/to.test.reb
%natives/as-pair.test.reb
%natives/func.test.reb
%natives/to-hex.test.reb
%file/clean-path.test.reb
%file/existsq.test.reb
%file/make-dir.test.reb
%file/open.test.reb
%file/file-typeq.test.reb
%math/absolute.test.reb
%math/add.test.reb
%math/and.test.reb
%natives/arcsine.test.reb
%natives/arctangent.test.reb
%math/complement.test.reb
%natives/cosine.test.reb
%natives/difference.test.reb
%math/divide.test.reb
%math/evenq.test.reb
%natives/exp.test.reb
%natives/log-10.test.reb
%natives/log-2.test.reb
%natives/log-e.test.reb
%math/mod.test.reb
%math/modulo.test.reb
%math/multiply.test.reb
%math/negate.test.reb
%math/negativeq.test.reb
%math/not.test.reb
%math/oddq.test.reb
%math/positiveq.test.reb
%math/power.test.reb
%math/random.test.reb
%math/remainder.test.reb
%math/round.test.reb
%natives/shift.test.reb
%math/signq.test.reb
%natives/sine.test.reb
%natives/square-root.test.reb
%math/subtract.test.reb
%natives/tangent.test.reb
%math/zeroq.test.reb
%reflectors/body-of.test.reb
%natives/protect.test.reb
%natives/unprotect.test.reb
%series/append.test.reb
%series/at.test.reb
%series/back.test.reb
%series/change.test.reb
%series/clear.test.reb
%series/copy.test.reb
%natives/difference.test.reb
%series/emptyq.test.reb
%natives/exclude.test.reb
%series/find.test.reb
%series/indexq.test.reb
%series/insert.test.reb
%natives/intersect.test.reb
%series/last.test.reb
%series/lengthq.test.reb
%series/next.test.reb
%series/ordinals.test.reb
%series/pick.test.reb
%series/poke.test.reb
%series/remove.test.reb
%series/reverse.test.reb
%series/select.test.reb
%series/skip.test.reb
%series/sort.test.reb
%series/split.test.reb
%series/tailq.test.reb
%series/trim.test.reb
%natives/union.test.reb
%natives/checksum.test.reb
%natives/compress.test.reb
%natives/decloak.test.reb
%string/decode.test.reb
%string/encode.test.reb
%natives/decompress.test.reb
%natives/dehex.test.reb
%system/system.test.reb
%system/file.test.reb
%system/gc.test.reb
%source/analysis.test.reb
