; Rebol []
; *****************************************************************************
; Title: Rebol core tests
; Copyright:
;     2012 REBOL Technologies
;     2013 Saphirion AG
; Author:
;     Carl Sassenrath, Ladislav Mecir, Andreas Bolka, Brian Hawley, John K
; License:
;     Licensed under the Apache License, Version 2.0 (the "License");
;     you may not use this file except in compliance with the License.
;     You may obtain a copy of the License at
;
;     http://www.apache.org/licenses/LICENSE-2.0
;
;     Unless required by applicable law or agreed to in writing, software
;     distributed under the License is distributed on an "AS IS" BASIS,
;     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;     See the License for the specific language governing permissions and
;     limitations under the License.
; *****************************************************************************
%parse-tests.r

%natives/action.test
%datatypes/binary.test
%datatypes/bitset.test
%datatypes/block.test
%datatypes/char.test
%datatypes/closure.test
%datatypes/datatype.test
%datatypes/date.test
%datatypes/decimal.test
%datatypes/email.test
%datatypes/error.test
%datatypes/event.test
%datatypes/file.test
%datatypes/function.test
%datatypes/get-path.test
%datatypes/get-word.test
%datatypes/gob.test
%datatypes/hash.test
%datatypes/image.test
%datatypes/integer.test
%datatypes/issue.test
%datatypes/list.test
%datatypes/lit-path.test
%datatypes/lit-word.test
%datatypes/logic.test
%datatypes/map.test
%datatypes/module.test
%datatypes/money.test
%datatypes/native.test
%natives/none.test
%datatypes/object.test
%datatypes/op.test
%datatypes/pair.test
%datatypes/paren.test
%datatypes/path.test
%datatypes/percent.test
%datatypes/port.test
%datatypes/refinement.test
%datatypes/set-path.test
%datatypes/set-word.test
%datatypes/string.test
%datatypes/symbol.test
%datatypes/time.test
%datatypes/tuple.test
%datatypes/typeset.test
%natives/unset.test
%datatypes/url.test
%datatypes/vector.test
%datatypes/word.test
%comparison/lesserq
%comparison/maximum-of
%comparison/equalq
%comparison/equivq
%comparison/sameq
%comparison/strict-equalq
%comparison/strict-not-equalq
%natives/bind.test
%context/boundq
%context/bindq
%natives/resolve.test
%natives/set.test
%natives/unset.test
%context/use
%context/valueq
%natives/all.test
%natives/any.test
%natives/apply.test
%natives/attempt.test
%natives/break.test
%natives/case.test
%natives/catch.test
%natives/compose.test
%natives/continue.test
%control/disarm
%natives/do.test
%natives/either.test
%control/else
%natives/exit.test
%natives/for.test
%control/forall
%natives/for-each.test
%natives/forever.test
%control/forskip
%natives/halt.test
%natives/if.test
%natives/loop.test
%natives/map-each.test
%natives/reduce.test
%natives/remove-each.test
%natives/repeat.test
%natives/return.test
%natives/switch.test
%natives/throw.test
%control/try
%natives/unless.test
%natives/until.test
%natives/wait.test
%natives/while.test
%natives/quit.test
%convert/as-binary
%convert/as-string
%convert/encode
%convert/load
%natives/mold.test
%natives/to.test
%natives/as-pair.test
%natives/func.test
%natives/to-hex.test
%file/clean-path
%file/existsq
%file/make-dir
%file/open
%file/file-typeq
%math/absolute
%math/add
%math/and
%natives/arcsine.test
%natives/arctangent.test
%math/complement
%natives/cosine.test
%natives/difference.test
%math/divide
%math/evenq
%natives/exp.test
%natives/log-10.test
%natives/log-2.test
%natives/log-e.test
%math/mod
%math/modulo
%math/multiply
%math/negate
%math/negativeq
%math/not
%math/oddq
%math/positiveq
%math/power
%math/random
%math/remainder
%math/round
%natives/shift.test
%math/signq
%natives/sine.test
%natives/square-root.test
%math/subtract
%natives/tangent.test
%math/zeroq
%reflectors/body-of
%natives/protect.test
%natives/unprotect.test
%series/append
%series/at
%series/back
%series/change
%series/clear
%series/copy
%natives/difference.test
%series/emptyq
%natives/exclude.test
%series/find
%series/indexq
%series/insert
%natives/intersect.test
%series/last
%series/lengthq
%series/next
%series/ordinals
%series/pick
%series/poke
%series/remove
%series/reverse
%series/select
%series/skip
%series/sort
%series/split
%series/tailq
%series/trim
%natives/union.test
%natives/checksum.test
%natives/compress.test
%natives/decloak.test
%string/decode
%string/encode
%natives/decompress.test
%natives/dehex.test
%system/system.test
%system/file.test
%system/gc.test
%source/analysis.test
