; Rebol []
; *****************************************************************************
; Title: Rebol core tests
; Copyright:
;     2012 REBOL Technologies
;     2013 Saphirion AG
; Author:
;     Carl Sassenrath, Ladislav Mecir, Andreas Bolka, Brian Hawley, John K
; License:
;     Licensed under the Apache License, Version 2.0 (the "License");
;     you may not use this file except in compliance with the License.
;     You may obtain a copy of the License at
;
;     http://www.apache.org/licenses/LICENSE-2.0
;
;     Unless required by applicable law or agreed to in writing, software
;     distributed under the License is distributed on an "AS IS" BASIS,
;     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;     See the License for the specific language governing permissions and
;     limitations under the License.
; *****************************************************************************
%parse-tests.r

%datatypes.action.r
%datatypes.binary.r
%datatypes.bitset.r
%datatypes.block.r
%datatypes.char.r
%datatypes.closure.r
%datatypes.datatype.r
%datatypes.date.r
%datatypes.decimal.r
%datatypes.email.r
%datatypes.error.r
%datatypes.event.r
%datatypes.file.r
%datatypes.function.r
%datatypes.get-path.r
%datatypes.get-word.r
%datatypes.gob.r
%datatypes.hash.r
%datatypes.image.r
%datatypes.integer.r
%datatypes.issue.r
%datatypes.list.r
%datatypes.lit-path.r
%datatypes.lit-word.r
%datatypes.logic.r
%datatypes.map.r
%datatypes.module.r
%datatypes.money.r
%datatypes.native.r
%datatypes.none.r
%datatypes.object.r
%datatypes.op.r
%datatypes.pair.r
%datatypes.paren.r
%datatypes.path.r
%datatypes.percent.r
%datatypes.port.r
%datatypes.refinement.r
%datatypes.set-path.r
%datatypes.set-word.r
%datatypes.string.r
%datatypes.symbol.r
%datatypes.time.r
%datatypes.tuple.r
%datatypes.typeset.r
%datatypes.unset.r
%datatypes.url.r
%datatypes.vector.r
%datatypes.word.r
%functions.comparison.lesserq.r
%functions.comparison.maximum-of.r
%functions.comparison.equalq.r
%functions.comparison.equivq.r
%functions.comparison.sameq.r
%functions.comparison.strict-equalq.r
%functions.comparison.strict-not-equalq.r
%functions.context.bind.r
%functions.context.boundq.r
%functions.context.bindq.r
%functions.context.resolve.r
%functions.context.set.r
%functions.context.unset.r
%functions.context.use.r
%functions.context.valueq.r
%functions.control.all.r
%functions.control.any.r
%functions.control.apply.r
%functions.control.attempt.r
%functions.control.break.r
%functions.control.case.r
%functions.control.catch.r
%functions.control.compose.r
%functions.control.continue.r
%functions.control.disarm.r
%functions.control.do.r
%functions.control.either.r
%functions.control.else.r
%functions.control.exit.r
%functions.control.for.r
%functions.control.forall.r
%functions.control.for-each.r
%functions.control.forever.r
%functions.control.forskip.r
%functions.control.halt.r
%functions.control.if.r
%functions.control.loop.r
%functions.control.map-each.r
%functions.control.reduce.r
%functions.control.remove-each.r
%functions.control.repeat.r
%functions.control.return.r
%functions.control.switch.r
%functions.control.throw.r
%functions.control.try.r
%functions.control.unless.r
%functions.control.until.r
%functions.control.wait.r
%functions.control.while.r
%functions.control.quit.r
%functions.convert.as-binary.r
%functions.convert.as-string.r
%functions.convert.encode.r
%functions.convert.load.r
%functions.convert.mold.r
%functions.convert.to.r
%functions.datatype.as-pair.r
%functions.define.func.r
%functions.onvert.to-hex.r
%functions.file.clean-path.r
%functions.file.existsq.r
%functions.file.make-dir.r
%functions.file.open.r
%functions.file.file-typeq.r
%functions.math.absolute.r
%functions.math.add.r
%functions.math.and.r
%functions.math.arcsine.r
%functions.math.arctangent.r
%functions.math.complement.r
%functions.math.cosine.r
%functions.math.difference.r
%functions.math.divide.r
%functions.math.evenq.r
%functions.math.exp.r
%functions.math.log-10.r
%functions.math.log-2.r
%functions.math.log-e.r
%functions.math.mod.r
%functions.math.modulo.r
%functions.math.multiply.r
%functions.math.negate.r
%functions.math.negativeq.r
%functions.math.not.r
%functions.math.oddq.r
%functions.math.positiveq.r
%functions.math.power.r
%functions.math.random.r
%functions.math.remainder.r
%functions.math.round.r
%functions.math.shift.r
%functions.math.signq.r
%functions.math.sine.r
%functions.math.square-root.r
%functions.math.subtract.r
%functions.math.tangent.r
%functions.math.zeroq.r
%functions.reflectors.body-of.r
%functions.secure.protect.r
%functions.secure.unprotect.r
%functions.series.append.r
%functions.series.at.r
%functions.series.back.r
%functions.series.change.r
%functions.series.clear.r
%functions.series.copy.r
%functions.series.difference.r
%functions.series.emptyq.r
%functions.series.exclude.r
%functions.series.find.r
%functions.series.indexq.r
%functions.series.insert.r
%functions.series.intersect.r
%functions.series.last.r
%functions.series.lengthq.r
%functions.series.next.r
%functions.series.ordinals.r
%functions.series.pick.r
%functions.series.poke.r
%functions.series.remove.r
%functions.series.reverse.r
%functions.series.select.r
%functions.series.skip.r
%functions.series.sort.r
%functions.series.split.r
%functions.series.tailq.r
%functions.series.trim.r
%functions.series.union.r
%functions.string.checksum.r
%functions.string.compress.r
%functions.string.decloak.r
%functions.string.decode.r
%functions.string.encode.r
%functions.string.decompress.r
%functions.string.dehex.r
%system.system.r
%system.file.r
%system.gc.r
%source.analysis.r
